version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    depends_on:
      - ollama
    command: tunnel --no-autoupdate --url http://ollama:11434 --metrics 0.0.0.0:2000
    environment:
      - TUNNEL_TRANSPORT_PROTOCOL=http2
    restart: unless-stopped

volumes:
  ollama_data: