#:schema node_modules/wrangler/config-schema.json
name = "bolt-diy-ai"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "bolt-diy-ai"

[env.staging]
name = "bolt-diy-ai-staging"

[build]
command = "npm run build"
watch_dir = "app"

[site]
bucket = "./build/client"
entry-point = "./build/server"

[[env.production.rules]]
type = "ESModule"
globs = ["**/*.js"]

[[env.staging.rules]]
type = "ESModule"
globs = ["**/*.js"]
