#:schema node_modules/wrangler/config-schema.json
name = "bolt-diy-ai"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Ollama Integration
[env.production.vars]
OLLAMA_API_BASE_URL = "https://your-ollama-server.com"

[env.staging.vars]
OLLAMA_API_BASE_URL = "https://your-ollama-server.com"

[env.production]
name = "bolt-diy-ai"

[env.staging]
name = "bolt-diy-ai-staging"

[build]
command = "npm run build"
watch_dir = "app"

main = "build/server/index.js"

[site]
bucket = "./build/client"

[[env.production.rules]]
type = "ESModule"
globs = ["**/*.js"]

[[env.staging.rules]]
type = "ESModule"
globs = ["**/*.js"]
