#:schema node_modules/wrangler/config-schema.json
name = "bolt-ollama"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = false

[env.production]
OLLAMA_API_BASE_URL = "https://your-ollama-server.com"
OLLAMA_REMOTE_URL = "https://your-ollama-server.com"
NODE_ENV = "production"

[env.preview]
OLLAMA_API_BASE_URL = "https://your-ollama-server.com"
OLLAMA_REMOTE_URL = "https://your-ollama-server.com"
NODE_ENV = "preview"
