// Client-side constants for reality transformation
export const REALITY_TRANSFORMATION_MODES = {
  VIRTUAL_TO_REAL: 'VIRTUAL_TO_REAL',
  SIMULATION_TO_ACTUAL: 'SIMULATION_TO_ACTUAL',
  CONCEPT_TO_IMPLEMENTATION: 'CONCEPT_TO_IMPLEMENTATION',
  IDEA_TO_CODE: 'IDEA_TO_CODE',
  DREAM_TO_APPLICATION: 'DREAM_TO_APPLICATION'
} as const;

export const TRANSFORMATION_PRIORITIES = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW'
} as const;

export const REALITY_LEVELS = {
  CONCEPTUAL: 'CONCEPTUAL',
  PROTOTYPE: 'PROTOTYPE',
  FUNCTIONAL: 'FUNCTIONAL',
  PRODUCTION: 'PRODUCTION',
  REAL_WORLD: 'REAL_WORLD'
} as const;